import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/CartContext/ProductContext";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
              

      <CartProvider >
      <body className={inter.className}>
      <Header/>
        {children}
        </body>

      </CartProvider>
    </html>
  );
}
